module VernSDK
  module Resources
    class Runs
      def create: (
        task_id: String,
        ?inputs: ::Hash[Symbol, top],
        ?profile_id: String,
        ?url: String,
        ?request_options: VernSDK::request_opts
      ) -> VernSDK::Models::RunCreateResponse

      def retrieve: (
        String id,
        ?request_options: VernSDK::request_opts
      ) -> VernSDK::Models::RunRetrieveResponse

      def initialize: (client: VernSDK::Client) -> void
    end
  end
end
